#!/bin/bash

dir="$(dirname "$0")"

PIPS="$dir/data/pips.list"

# Install python packages using the list of packages 'data/pips.list'
function pips {
  show_info 'Updating pip...'
  sudo pip install pip --upgrade
	if (eval `resize` && whiptail \
		--title "Python packages" \
		--yesno "Current list of python packages to install: \n\n$(cat $PIPS) \n\nProceed with installation?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		show_info 'Installing...'
		show_warning 'Requires root privileges'
		# For loop for installing
		for PACKAGE in $(cat $PIPS)
		do
			# Check if package is installed
			PKGCHECK=$(pip list --format=legacy --uptodate | grep -E "^$PACKAGE\s")
			if [ "" == "$PKGCHECK" ]; then
				show_info "Package '$PACKAGE' is not up-to-date. Installing..."
				# Install package
				sudo pip install $PACKAGE --upgrade
				show_success 'Done.'
			else
				show_success "Package '$PACKAGE' is installed and up-to-date."
			fi
		done
		show_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of python packages is complete." 8 44
		main
	else
		main
	fi
}
